class ModulesData {
  static const Map<String, Map<String, List<String>>> data = {
    'Computing & Information Systems (CIS)': {
      'Semester I': [
        'Fundamentals of Information Systems',
        'Structured Programming Techniques',
        'Structured Programming Practicum',
        'Theories of Information Systems',
        'Computer System Organization',
        'Foundations of Web Technologies',
        'Personal Productivity with IT',
        'Fundamentals of Mathematics',
        'Statistics & Probability Theory',
        'Communication Skills I',
        'Academic Integrity',
        'General English I',
      ],
      'Semester II': [
        'Object Oriented Programming',
        'OOP Practicum',
        'Emerging IS Technologies',
        'Database Systems',
        'DBMS Practicum',
        'System Analysis & Design',
        'Social & Professional Issues',
        'Human Computer Interaction',
        'Information Assurance & Security',
        'Software Project Initiation & Planning',
        'Advanced Mathematics',
        'Communication Skills II',
        'General English II',
      ],
      'Semester III': [
        'Object Oriented Analysis & Design',
        'Data Structures & Algorithms',
        'IT Governance',
        'Software Engineering',
        'IS Risk Management',
        'IS Sustainability',
        'Management Information Systems',
        'E-Business',
        'Digital Innovation',
        'Academic English I',
      ],
      'Semester IV': [
        'IT Auditing',
        'Web Application Development',
        'Operating Systems',
        'System Administration',
        'Computer Networks',
        'Business Process Management',
        'Capstone Project',
        'Academic English II',
      ],
      'Semester V': [
        'Information Systems Project for Community',
        'Enterprise Architecture',
        'Business Intelligence',
        'Business Process Modeling',
        'Business English',
        'Mobile App Development',
        'GIS',
        'Machine Learning',
      ],
      'Semester VI': [
        'Industrial Training (Compulsory)',
      ],
      'Semester VII': [
        'Research Methodologies',
        'IT Law',
        'Business Process Simulation',
        'Enterprise Modelling Ontologies',
        'Organizational Behavior & Management',
        'Cloud Computing',
        'Mobile Application Development',
        'Web Service Technologies',
        'GIS',
        'Statistical Distribution & Inferences',
        'Advanced Programming Practicum',
        'Machine Learning',
      ],
      'Semester VIII': [
        'Research Project in IS',
        'Business/IT Alignment',
        'Human Resource Management',
        'Scientific Communication',
        'IS Economics',
        'Computer System Security',
        'Supply Chain Management',
        'Advanced Computer Networks',
        'Process Mining',
        'Digital Business Model',
        'Game Development',
      ],
    },
    'Software Engineering (SE)': {
      'Semester I': [
        'Computer Organization',
        'Programming Fundamentals',
        'Requirements Fundamentals',
        'Software Process Concepts',
        'Social & Professional Issues',
        'Fundamentals of Mathematics',
        'Fundamentals of Statistics',
        'Communication Skills I',
        'Academic Integrity',
        'General English I',
      ],
      'Semester II': [
        'Algorithms, Data Structures & Complexity',
        'Database Management Systems',
        'Operating Systems Basics',
        'Object Oriented Programming',
        'Requirement Specification & Documentation',
        'Software Process Implementation',
        'Analysis Fundamentals',
        'Advanced Mathematics',
        'Communication Skills II',
        'General English II',
      ],
      'Semester III': [
        'Network Protocols',
        'Formal Methods',
        'Object Oriented Analysis & Design',
        'Requirements Validation',
        'Software Design Concepts',
        'Web Systems & Technologies',
        'Software Engineering Foundations',
        'Academic English I',
      ],
      'Semester IV': [
        'Security Fundamentals',
        'Software Verification & Validation',
        'Software Configuration Management',
        'Software Project Management',
        'Human Computer Interaction Design',
        'Projects in Web Systems & Technologies',
        'Industrial Inspection',
        'Risk Management',
        'Communication Skills',
        'Management Information Systems',
        'Academic English II',
      ],
      'Semester V': [
        'Computer & Network Security',
        'Software Testing',
        'Product Assurance',
        'Mini Project',
        'Evolution Processes & Activities',
        'Business English',
        'IT Auditing',
        'HRM',
        'GIS',
        'Logistics & Transportation Management',
        'Business Intelligence',
      ],
      'Semester VI': [
        'Community Project',
        'Cloud Computing',
        'Parallel & Distributed Systems',
        'Advanced DBMS',
        'Software Architecture',
        'Software Design Patterns',
        'Software Design Evaluation',
        'Current Topics in SE',
        'Enterprise Modeling Ontologies',
        'Software Engineering Economics',
        'Social Computing',
        'Semantic Web',
        'Robotics',
      ],
      'Semester VII': [
        'Industrial Training',
      ],
      'Semester VIII': [
        'Research Project',
        'Research Methods',
        'Service Oriented Architecture',
        'Problem Analysis & Reporting',
        'Machine Learning',
        'Mobile Computing',
        'Refactoring',
        'Game Designing & Development',
        'Data Mining',
        'Big Data Analytics',
        'Artificial Intelligence',
      ],
    },
    'Data Science (DS)': {
      'Semester I': [
        'Introduction to Data Science',
        'Programming Fundamentals',
        'Calculus',
        'Introduction to Statistics',
        'Database Management Systems',
        'Communication Skills I',
        'Academic Integrity',
        'General English I',
      ],
      'Semester II': [
        'Web Programming I',
        'Linear Algebra',
        'Probability & Statistics',
        'Object Oriented Programming',
        'Capstone Project in Data Science I',
        'Analysis of Algorithms',
        'System Analysis & Design',
        'Data Pre-Processing',
        'Communication Skills II',
        'General English II',
      ],
      'Semester III': [
        'Probability Theory',
        'Regression Analysis',
        'Multivariate Calculus',
        'Real World Analytics',
        'Computer Networking',
        'Data Warehousing',
        'Web Programming II',
        'Academic English I',
      ],
      'Semester IV': [
        'Advanced DBMS',
        'Scientific Writing & Documentation',
        'Software Engineering',
        'Data Visualization',
        'Capstone Project in Data Science II',
        'Applied Data Mining',
        'Social & Professional Issues in Computing',
        'Business Intelligence',
        'Discrete Mathematics',
        'Artificial Intelligence',
        'Academic English II',
      ],
      'Semester V': [
        'Semantic Web',
        'Time Series Analysis & Forecasting',
        'Information Security',
        'Machine Learning',
        'Linear Programming',
        'Graph Theory',
        'Business English',
        'Image Processing',
        'Mobile Computing',
        'Bioinformatics',
        'HRM',
        'Parallel & Distributed Computing',
      ],
      'Semester VI': [
        'Introduction to Deep Learning',
        'Bayesian Learning & Graphical Models',
        'Mathematical Optimization',
        'Industrial Training',
        'Web Services',
        'Cloud Computing',
        'Business Process Management',
        'Software Quality Assurance',
        'Fraud & Anomaly Detection',
      ],
      'Semester VII': [
        'Research Method',
        'Advanced Deep Learning',
        'Emerging Trends in Data Science',
        'Numerical Methods',
        'Natural Language Processing',
        'Entrepreneurship & Innovation',
        'IoT',
        'Design Patterns & Anti-patterns',
        'Ontology Engineering',
        'Blockchain & Cryptocurrency',
      ],
      'Semester VIII': [
        'Research Project in Data Science',
        'Information Retrieval & Web Analytics',
        'Reinforcement Learning',
        'Computational Intelligence',
        'Business Analytics & Applications',
        'GIS',
        'Digital Forensics',
        'Business Process Simulation',
        'Robotics',
      ],
    },
  };
}
